### ISSUE TITLE
Proxy & TLS Certificate

### ISSUE THREAD

**Issue by ashersnavely** [simon987/Architeuthis#1]
it really do be like that sometimes tho

**Comment by simon987** [comment]
Hi, thank you for your input.
Could you elaborate please?

**Comment by ashersnavely** [comment]
Oh, I just realized I posted this issue on your github repo!

Too many windows open I suppose haha, I meant to post it as a quick
reminder of the issue on my partner's repo.

Really sorry about this, I'll see if I can remove that for you or if not
feel free to close the issue of course :)

I believe this would be an error with my setup not your tool, and thanks
for the tool by the way its been great.

Anyways, have a good day and I'll let you know if I come across any actual
issues -
    Ash

**Comment by simon987** [comment]
Oh, no worries.
Now I'm curious on how you're using this repo, if it's something public and you don't mind sharing of course @ashersnavely

**Comment by ashersnavely** [comment]
It's not public yet, were hoping to get a paper published on the project.

Hopefully it will be done pretty soon though and I can send you a link then if you want.

**Comment by simon987** [comment]
Yeah, please let me know when that happens :)
(And don't hesitate if you have a real issue with this project :smile: )
