### ISSUE TITLE
Status 500 Internal Server Error on all calls through Architeuthis

### ISSUE THREAD

**Issue by B-McDonnell** [simon987/Architeuthis#2]
Error occurs in function `isPermanentError` at lines 69-73 in `errors.go`. Error message is as follows:
`FIXME: isPermanentError; opErr == nil`

Always returns status code 500.

Tests run with input from ProxyBroker.

Steps to reproduce:
1. (with default config.json, docker-compose.yaml) `docker-compose up`
2. Confirm that Architeuthis is running at 127.0.0.1:5050
2. `python3 import_from_broker.py http://127.0.0.1:5050`
3. Execute any GET via Architeuthis

Running on Ubuntu 20.04.2 LTS

**Comment by simon987** [comment]
Hi,
thanks for the detailed info. I'm overcommitted in many projects right now, I probably will not have time to look at this  for a few weeks, sorry. But if anyone else is willing to look at this I can review a PR

**Comment by B-McDonnell** [comment]
I may have time to investigate this later in the week.

**Comment by B-McDonnell** [comment]
Not sure what the source of the error was, but removing all of my docker images, reinstalling docker, and re-running a fresh instance of Architeuthis solved the issue.
