### ISSUE TITLE
Every other connection fails

### ISSUE THREAD

**Issue by caj-larsson** [simon987/Architeuthis#3]
I'm having an interesting issue where it seems something crashes every other connection. Could this be because I do not have it connected to an influx server?

```
~ curl -I --proxy localhost:5050 example.org
curl: (7) Failed to connect to localhost port 5050 after 10 ms: Connection refused
~ curl -I --proxy localhost:5050 example.org
HTTP/1.1 200 OK
Content-Length: 6996
Content-Type: text/html
Date: Tue, 10 Feb 1970 15:45:58 GMT
Expires: 0
```
And this repeats perfectly.

I also can't access `/stats`, I get a panic on invalid memory access.

**Comment by caj-larsson** [comment]
I added a influxdb but it made every 3 request succeed instead

**Comment by simon987** [comment]
Hi this project is no longer really being maintained (by me) sorry. Are you also running redis? I might have updated the app without updating the documentation but IIRC you need redis to be running for this to work. Do you have the same issue when running with compose?

**Comment by caj-larsson** [comment]
I am and I'm sure it's working as my proxies are persistent through restarts of architheuthis. Could it be a dependency update thing?

**Comment by simon987** [comment]
Hm, I'm not sure. If you're building the app with docker and use the same go version I don't see why that would be a dependency issue

**Comment by caj-larsson** [comment]
I found this was actually two different issues neither of which serious.

The first one was that the stats-page template was not included in the docker image. Making the stats route crash with a worse then expected looking error.

The second was that my kubernetes loadbalancer was misbehaving and the round-robin over the nodes would only work for one of them.
